Gem shubhamkumar
Gemini-Solutions/MIS_Automation pull request #12
Opened 2023-02-07 15:14 UTC by gem-shubhamkumar

@gem-rishabhrastogi, Please review my code.

2023-02-08 06:39 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/MIS/StepDefinition/LeaveManagementSteps.java
> +        DriverAction.waitSec(2);
Replace hard-coded waits with dynamic waits

2023-02-08 06:41 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/MIS/StepDefinition/LeaveManagementSteps.java
> +        DriverAction.click(LeaveManagementLocators.menu_parentTabs(parentTab), parentTab);
Before clicking an element, either enclose it within try-catch block or validate the element's existence.

2023-02-08 06:47 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/MIS/StepDefinition/LeaveManagementSteps.java
> +        switch (fieldType) {
Switch statement is used for executing one statement from multiple conditions. If you've only one condition, it doesn't make sense to use switch case. Your purpose can be solved by using a simple if-else statement also.

2023-02-08 06:52 UTC, gem-shubhamkumar commented on src/main/java/com/qa/MIS/StepDefinition/LeaveManagementSteps.java
> +        switch (fieldType) {
Sure Rishabh, I have created switch block wrt future perspective. In future, if any case come in picture, I will add that otherwise change it to if-else.

2023-02-08 06:55 UTC, gem-rishabhrastogi commented on src/main/resources/features/LeaveManagement.feature
> +    When User is on MIS Home Page
This condition is already fulfilled in "Given" test step. I suggest we should skip this step and start with "When" keyword in the next step.

2023-02-08 06:57 UTC, gem-rishabhrastogi commented on src/main/resources/features/LeaveManagement.feature
> +    And Verify "<tab>" displays
Replace statements like "displays" with "is displayed"

2023-02-08 06:58 UTC, gem-rishabhrastogi commented on src/main/resources/features/LeaveManagement.feature
> +    Then select compOff date <dateIndex> for "<date>" field
Follow proper gherkin language conventions while creating test steps in feature file. You should always start a sentence with an Upper Case letter

2023-02-08 07:00 UTC, gem-shubhamkumar commented on src/main/resources/features/LeaveManagement.feature
> +    When User is on MIS Home Page
In ` Given` Step, I have written only for entering credentials. after that I have used `When` keyword for verifying MIS homepage. In that step I am verifying URL.

2023-02-08 07:02 UTC, gem-rishabhrastogi requested changes
Added some suggestions. Please work on those.

2023-02-14 07:34 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/MIS/StepDefinition/LeaveManagementSteps.java
> +        DriverAction.click(LeaveManagementLocators.field_outingCalender(field), elementLabel);
Create a separate function fn_isEnabledClick(By loc) and validate the element existence before clicking on it in that function.

2023-02-14 07:37 UTC, gem-rishabhrastogi commented on src/main/resources/features/LeaveManagement.feature
> +
Refer Line No. 222 in the same file. We shouldn't be ending a scenario with When/And test step, rather it should be Then/And as the ending test step of the test scenario.

2023-02-14 07:37 UTC, gem-rishabhrastogi requested changes
Added my comments. Please work on those.

2023-02-14 10:30 UTC, gem-rishabhrastogi approved these changes
Good to go @gemini-akashGarg

2023-02-14 11:13 UTC, merged