updated dashboard and referal module- 17feb
Gemini-Solutions/MIS_Automation pull request #41
Opened 2023-02-20 07:28 UTC by gem-divyamadan

Hi Neeraj,
Please get the code reviewed for two modules.
1.DashboardProfile
2.Referral
Thanks

2023-02-22 08:47 UTC, gem-divyamadan commented
Hi Neeraj,
Please review the code for Dashboard profile and referral.
Thanks

2023-02-23 03:58 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +            }
GemTestReporter.addTestStep("ERROR", "SOME ERROR OCCURRED" + e, STATUS.FAIL, DriverAction.takeSnapShot());

Please use proper error definition

2023-02-23 04:00 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +        DriverAction.click(refEmail, "referral email text");
either verify of surround selenium click function in try catch statement for every instance

2023-02-23 04:04 UTC, Gem-NeerajSingh requested changes
Please update code as per given comments

2023-02-23 06:30 UTC, gem-divyamadan commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +        DriverAction.click(refEmail, "referral email text");
Done pls have look.!

2023-02-23 06:31 UTC, gem-divyamadan commented
Changes made

2023-02-23 07:28 UTC, gem-divyamadan commented
Done changes 23feb23

2023-02-23 09:07 UTC, Gem-NeerajSingh approved these changes

2023-02-28 07:02 UTC, Gem-NeerajSingh commented on src/main/resources/features/Referal.feature
> +          Scenario: Validation of wrong format upload pop
pop up

2023-02-28 07:14 UTC, gem-divyamadan commented on src/main/resources/features/Referal.feature
> +          Scenario: Validation of wrong format upload pop
Hi Neeraj,
Pop up done & one locator added in dashboard.
Thanks

2023-02-28 07:22 UTC, Gem-NeerajSingh approved these changes

2023-03-02 12:10 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/DashboardProfileSteps.java
>          //DriverAction.waitSec(10);
Please Remove Commented Code

2023-03-02 12:30 UTC, closed without merging