Gem jar divya
Gemini-Solutions/MIS_Automation pull request #43
Opened 2023-03-02 12:31 UTC by gem-divyamadan

comments removed as suggested.

2023-03-02 15:00 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/locators/DashboardProfileLocator.java
> +  public static By selectNextArrow=By.xpath("//body[1]/div[16]/div[1]/table[1]/thead[1]/tr[2]/th[3]");
use dynamic xpath  , Avoid using absolute xpaths

2023-03-02 15:05 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/DashboardProfileSteps.java
> +        DriverAction.click(clickOnChangeDetails, "click on edit details button");
use element visibility check or  try catch

2023-03-02 15:05 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/DashboardProfileSteps.java
> +        DriverAction.click(clickOnChangeDetails, "click on edit details button");
use element visibility check or  try catch

2023-03-02 15:05 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/DashboardProfileSteps.java
> +        DriverAction.click(updateMobileNo, "click on update mobile no. button");
use element visibility check or  try catch

2023-03-02 15:05 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/DashboardProfileSteps.java
> +        DriverAction.typeText(enterExtNo, "11");
use element visibility check or  try catch

2023-03-02 15:06 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +            GemTestReporter.addTestStep("ERROR", "SignIn error" + e, STATUS.FAIL, DriverAction.takeSnapShot());
please use proper error logging

2023-03-02 15:08 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +        DriverAction.click(refEmail, "referral email text");
use element visibility check or  try catch

2023-03-02 15:08 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +        DriverAction.typeText(refEmail, "abcde");
use element visibility check or  try catch

2023-03-02 15:08 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +        DriverAction.click(refSaveButton, "click on save button under referral");
use element visibility check or  try catch

2023-03-02 15:11 UTC, Gem-NeerajSingh requested changes
Changes required

2023-03-03 09:42 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/locators/DashboardProfileLocator.java
> +    public static By selectNextArrow=By.xpath("//body[1]/div[16]/div[1]/table[1]/thead[1]/tr[2]/th[3]");
Use dynamic xpath (Avoid using absolute xpath)

2023-03-03 09:43 UTC, Gem-NeerajSingh approved these changes

2023-03-03 12:01 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/DashboardProfileSteps.java
> +           GemTestReporter.addTestStep("ERROR", "not found SignIn" + e, STATUS.FAIL,DriverAction.takeSnapShot());
Please leave proper error logging

2023-03-03 12:03 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/DashboardProfileSteps.java
> +       }
please use proper error logging

2023-03-03 12:14 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/mis/stepdefinition/ReferalStep.java
> +            GemTestReporter.addTestStep("ERROR", "not found verify JD window" + e, STATUS.FAIL, DriverAction.takeSnapShot());
avoid shortforms in error logging

2023-03-03 12:15 UTC, Gem-NeerajSingh requested changes
PFB

2023-03-06 06:34 UTC, closed without merging

2023-03-06 06:34 UTC, gem-divyamadan commented
Done