6 And 7 Feb MIS_Automation
Gemini-Solutions/MIS_Automation pull request #7
Opened 2023-02-07 09:11 UTC by Gem-Shrutissingh

@gem-rishabhrastogi

2023-02-07 10:53 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/MIS_Automation/StepDefination/StepDefination.java
> +        System.out.println("Error msg appeared");
Replace System.out.print statements with Reporting functionalities

2023-02-07 10:55 UTC, gem-rishabhrastogi commented on src/main/java/com/qa/MIS_Automation/StepDefination/StepDefination.java
> +        DriverAction.click(Locators.okBtn);
Before clicking an element, either enclose it within try-catch block or validate the existence of element.

2023-02-07 10:59 UTC, gem-rishabhrastogi commented on src/main/resources/features/MIS_Automation.feature
> +    Given User clicks on tab "<parent Tab>" and "<child Tab>"
Refrain from using spaces between argument names. For example, replace "parent Tab" with "parentTab"

2023-02-07 11:00 UTC, gem-rishabhrastogi commented on src/main/resources/features/MIS_Automation.feature
> +    Then User verifies element "<FirstElement>"
The first character of all the arguments should be in small case. Replace "FirstElement" with "firstElement".

2023-02-07 11:02 UTC, gem-rishabhrastogi requested changes
I've added some suggestions in a couple of files. Please work on those.

2023-02-07 11:05 UTC, Gem-Shrutissingh commented
Hi Rishabh ;

Thanks for the review will work on that.


Thanks & Regards,
Shruti Singh

Software Engineer - L1
M: +91 7895909198

Quality Assurance Department


[cid:9e47948a-cda9-46a7-8ea5-4bd09295f615]

LinkedIn<https://www.linkedin.com/company/gemini-solutions-india/mycompany/?viewAsMember=true> | Facebook<https://www.facebook.com/gemsolindia> | Instagram<https://www.instagram.com/gemini.solutions/> | Glassdoor<https://www.glassdoor.co.in/Overview/Working-at-Gemini-Solutions-EI_IE1333027.11,27.htm>


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: gem-rishabhrastogi ***@***.***>
Sent: Tuesday, February 7, 2023 4:32:12 PM
To: Gemini-Solutions/MIS_Automation ***@***.***>
Cc: Shruti Singh ***@***.***>; Author ***@***.***>
Subject: Re: [Gemini-Solutions/MIS_Automation] 6 And 7 Feb MIS_Automation (PR #7)


@gem-rishabhrastogi requested changes on this pull request.

I've added some suggestions in a couple of files. Please work on those.

—
Reply to this email directly, view it on GitHub<https://github.com/Gemini-Solutions/MIS_Automation/pull/7#pullrequestreview-1286877112>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A2XABMXIYUO4A2EGZ3AOBGTWWITTJANCNFSM6AAAAAAUTWGDTE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-02-09 11:07 UTC, gem-rishabhrastogi approved these changes
Good to go @gemini-akashGarg

2023-02-09 11:47 UTC, merged