6th Feb - Charu
Gemini-Solutions/MIS_Automation pull request #8
Opened 2023-02-07 09:18 UTC by gem-charugarg

Ayush Mathur

2023-02-07 11:21 UTC, gem-ayushmathur approved these changes

2023-02-07 11:34 UTC, gem-ayushmathur requested changes
Added my comments where changes are required.

2023-02-07 11:34 UTC, gem-ayushmathur commented on src/main/resources/features/Login.feature
> +  Scenario: User verifies elements of Login page
Repeating scenario

2023-02-07 11:34 UTC, gem-ayushmathur commented on src/main/resources/features/Login.feature
> +    Given Enter username "<uname>"
@Given @When @Then steps standard are not followed.

2023-02-08 11:36 UTC, gem-charugarg commented
@gem-ayushmathur Please review this one.

2023-02-08 11:46 UTC, gem-ayushmathur approved these changes
Approved @gemini-akashGarg

2023-02-09 05:41 UTC, merged